platform :ios, '12.0'
use_frameworks!

target 'CallSample' do
#  pod 'VoxSDK', '~> 1.0.35'
  pod 'VoxSDK'
  pod 'VoxWebRTC'
  pod 'AWSCore', '~> 2.10.0'
  pod 'AWSS3'
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
