platform :ios, '12.0'
use_frameworks!

target 'LoginSample' do
  pod 'VoxSDK'
  pod 'VoxWebRTC', '~> 1.0.4'
  pod 'AWSCore', '2.7.3'
  pod 'AWSS3', '2.7.3'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end