# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

target 'ChatSample' do
  # Pods for ChatSample
  pod 'VoxSDK', '~> 1.0.35'
  pod 'VoxWebRTC', '~> 1.0.3'
  pod 'AWSCore', '~> 2.7.0'
  pod 'AWSS3', '~> 2.7.0'
#  pod  'InStatDownloadButton'

#  target 'ChatSampleTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'ChatSampleUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
